services:
  s9ee:
    image: aixpand/exe_eng:develop
    container_name: hyfy_exe_eng
    restart: always
    env-file: .env
    gpus: all
    volumes:
      - ee_vol:/exe_eng/_local_cache
    labels:
      - "com.centurylinklabs.watchtower.enable=true"         
      - "com.centurylinklabs.watchtower.stop-signal=SIGINT"          

  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=60 # Check every 1 minute
      - WATCHTOWER_CHECK_NEW_IMAGES=true      
      - WATCHTOWER_LABEL_ENABLE=true        


volumes:
  ee_vol:
    name: ee_vol
